CREATE DATABASE TIENDA_VARIEDAD_YERBAR_Y_BARRO;

CREATE TABLE PRODUCTOS (
    id_producto INT,
    nombre VARCHAR(50) NOT NULL,
    descripcion TEXT, 
    precio DECIMAL(10, 2),
    stock INT,
    id_proveedor INT   
);

CREATE TABLE CATEGORIA (
ID_CATEGORIA INT,
NOMBRE VARCHAR(50)NOT NULL);


CREATE TABLE PROVEEDORES (
ID_PROVEDOORES INT,
NOMBRE VARCHAR (50)NOT NULL,
CONTACTO INT
);

CREATE TABLE CLIENTES (
ID_CLIENTES VARCHAR(50) NOT NULL,
CORREO VARCHAR(50) NOT NULL,
TELEFONO INT
);

CREATE TABLE VENTA  (
ID_VENTA INT,
FECHA DATE NOT NULL,
ID_CLIENTE INT,
TOTAL DECIMAL(10,2)
);

CREATE TABLE FACTURA (
ID_FACTURA INT,
ID_VENTA INT,
ID_PRODUCTO INT,
CANTIDAD INT,
PRECIO_UNITARIO INT );

INSERT INTO Productos (id_producto, nombre, descripcion, precio, stock, id_proveedor)
VALUES
(1, 'Producto 1', 'Descripción del Producto 1', 20.00, 100, 1),
(2, 'Producto 2', 'Descripción del Producto 2', 15.00, 200, 2),
(3, 'Producto 3', 'Descripción del Producto 3', 25.00, 50, 1);


